/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package sistemadegerenciamentodetarefas.view;

import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import sistemadegerenciamentodetarefas.model.TarefaAcademica;
import sistemadegerenciamentodetarefas.model.TarefaProfissional;
import sistemadegerenciamentodetarefas.repository.TarefaAcademicaRepository;
import sistemadegerenciamentodetarefas.repository.TarefaProfissionalRepository;

/**
 *
 * @author gustavo
 */
public class JanelaOpcaoRelatorios extends javax.swing.JInternalFrame {

    private static JanelaOpcaoRelatorios instancia;
    private JanelaPrincipal janelaPrincipal;
    JanelaTarefasAcademicas janelaTarefasAcademicas;
    JanelaTarefasProfissionais janelaTarefasProfissionais;
    
    public JanelaOpcaoRelatorios(JanelaPrincipal janelaPrincipal) {
        initComponents();
        this.janelaPrincipal = janelaPrincipal;  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAcademica = new javax.swing.JButton();
        btnProfissional = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        jLabel1.setText("Escolha uma das opções de tarefas para ser gerado seu relatório");

        btnAcademica.setText("Academica");
        btnAcademica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcademicaActionPerformed(evt);
            }
        });

        btnProfissional.setText("Profissional");
        btnProfissional.setToolTipText("");
        btnProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfissionalActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAcademica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProfissional)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFechar))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcademica)
                    .addComponent(btnProfissional)
                    .addComponent(btnFechar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcademicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcademicaActionPerformed
        // TODO add your handling code here:
        try {
            janelaTarefasAcademicas = new JanelaTarefasAcademicas(this);
            TarefaAcademicaRepository tarefaRepository = new TarefaAcademicaRepository();
            List<TarefaAcademica> listaTarefas = tarefaRepository.selecionarTodos(janelaPrincipal.conexaoMySQL.connection, 100);
            janelaTarefasAcademicas.carregarTarefas(listaTarefas);
            
            if (!janelaTarefasAcademicas.isVisible()) {
                janelaPrincipal.getDesktopPane().add(janelaTarefasAcademicas);
                janelaTarefasAcademicas.setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);
                janelaTarefasAcademicas.setVisible(true);
                int x = (janelaPrincipal.getDesktopPane().getWidth() - janelaTarefasAcademicas.getWidth()) / 2;
                int y = (janelaPrincipal.getDesktopPane().getHeight() - janelaTarefasAcademicas.getHeight()) / 2;
                janelaTarefasAcademicas.setLocation(x, y);
            }

            janelaTarefasAcademicas.setSelected(true);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,
                    "Erro ao abrir a janela de relatórios de tarefas acadêmicas: " + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAcademicaActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        fecharJanela();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfissionalActionPerformed
        // TODO add your handling code here:
        try {
            janelaTarefasProfissionais = new JanelaTarefasProfissionais(this);
            TarefaProfissionalRepository tarefaRepository = new TarefaProfissionalRepository();
            List<TarefaProfissional> listaTarefas = tarefaRepository.selecionarTodos(janelaPrincipal.conexaoMySQL.connection, 100);
            janelaTarefasProfissionais.carregarTarefas(listaTarefas);
            
            if (!janelaTarefasProfissionais.isVisible()) {
                janelaPrincipal.getDesktopPane().add(janelaTarefasProfissionais);
                janelaTarefasProfissionais.setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);
                janelaTarefasProfissionais.setVisible(true);
                int x = (janelaPrincipal.getDesktopPane().getWidth() - janelaTarefasProfissionais.getWidth()) / 2;
                int y = (janelaPrincipal.getDesktopPane().getHeight() - janelaTarefasProfissionais.getHeight()) / 2;
                janelaTarefasProfissionais.setLocation(x, y); 
            }

            janelaTarefasProfissionais.setSelected(true);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,
                    "Erro ao abrir a janela de relatórios de tarefas profissionais: " + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnProfissionalActionPerformed
    
    private void fecharJanela(){
        instancia = null;
        dispose();
    }
    
    public static JanelaOpcaoRelatorios getInstancia(JanelaPrincipal janelaPrincipal){
        if(instancia == null)
            instancia = new JanelaOpcaoRelatorios(janelaPrincipal);
        return instancia;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcademica;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnProfissional;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
