/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package sistemadegerenciamentodetarefas.view;

import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;
import sistemadegerenciamentodetarefas.model.TarefaAcademica;
import sistemadegerenciamentodetarefas.repository.TarefaAcademicaRepository;


/**
 *
 * @author gustavo
 */

public class JanelaTarefasAcademicas extends javax.swing.JInternalFrame {

    private static JanelaTarefasAcademicas instancia;
    private JanelaOpcaoRelatorios janelaOpcaoRelatorios;
    private JanelaPrincipal janelaPrincipal;
    
    public JanelaTarefasAcademicas(JanelaOpcaoRelatorios janelaOpcaoRelatorios, JanelaPrincipal janelaPrincipal) {
        initComponents();
        this.janelaOpcaoRelatorios = janelaOpcaoRelatorios;
        this.janelaPrincipal = janelaPrincipal;
    }
    
    public JanelaTarefasAcademicas() {
        setTitle("Tarefas Acadêmicas");
        setSize(400, 300);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
    }

    public void carregarTarefas(List<TarefaAcademica> listaTarefas) {
        DefaultTableModel modeloTabela = (DefaultTableModel) tableTarefas.getModel();
        modeloTabela.setRowCount(0);
        
        if (listaTarefas.isEmpty()) {
            System.out.println("Nenhuma tarefa para carregar.");
            JOptionPane.showMessageDialog(null,
                    "Nenhuma tarefa encontrada",
                    "Opção relatório",
                    JOptionPane.ERROR_MESSAGE);
        }

        for (TarefaAcademica tarefa : listaTarefas) {
            modeloTabela.addRow(new Object[] {
                    tarefa.getId(),
                    tarefa.getNomeTarefa(),
                    tarefa.getDescricaoTarefa(),
                    tarefa.getData(),
                    tarefa.getStatus(),
                    tarefa.getMateria(),
                    tarefa.getProfessor()
            });
            System.out.println("Tarefa carregada: " + tarefa.getNomeTarefa());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableTarefas = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();
        txtProcurar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Relatório Tarefas Acadêmicas");
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));

        tableTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tarefa", "Descrição", "Data", "Status", "Matéria", "Professor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableTarefas);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addGap(393, 393, 393))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnFechar)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        fecharJanela();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        DefaultTableModel modeloTabela = (DefaultTableModel) tableTarefas.getModel();
        modeloTabela.setRowCount(0);
        String nome = txtProcurar.getText().trim();
        TarefaAcademicaRepository tarefaAcademicaRepository = new TarefaAcademicaRepository();
        List<TarefaAcademica> tarefaAcademica = tarefaAcademicaRepository.buscarPorNome(janelaPrincipal.conexaoMySQL.connection, nome);
        
        if (tarefaAcademica.isEmpty()) {
            System.out.println("Nenhuma tarefa para carregar.");
            JOptionPane.showMessageDialog(null,
                    "Nenhuma tarefa encontrada",
                    "Opção relatório",
                    JOptionPane.ERROR_MESSAGE);
        }

        for (TarefaAcademica tarefa : tarefaAcademica) {
            modeloTabela.addRow(new Object[] {
                    tarefa.getId(),
                    tarefa.getNomeTarefa(),
                    tarefa.getDescricaoTarefa(),
                    tarefa.getData(),
                    tarefa.getStatus(),
                    tarefa.getMateria(),
                    tarefa.getProfessor()
            });
            System.out.println("Tarefa carregada: " + tarefa.getNomeTarefa());
        }    
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void fecharJanela(){
        instancia = null;
        dispose();
    }
    
    public static JanelaTarefasAcademicas getInstancia(JanelaOpcaoRelatorios janelaOpcaoRelatorios, JanelaPrincipal janelaPrincipal){
        if(instancia == null)
        instancia = new JanelaTarefasAcademicas(janelaOpcaoRelatorios, janelaPrincipal);
        return instancia;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTarefas;
    private javax.swing.JTextField txtProcurar;
    // End of variables declaration//GEN-END:variables
}
